const teachers = [
    {
        id: 1,
        name: 'Jüri Kurvits',
        email: 'juri.kurvits1234@gmail.com',
        room: '301',
        birthdate: '1990-05-15',
        subject: 'Praktiline Matemaatika',
    },
    {
        id: 2,
        name: 'Juho Kalberg',
        email: 'juho.kalberg1234@gmail.com',
        room: '204',
        birthdate: '1985-03-22',
        subject: 'Veebirakenduste loomine',
    },
    {
        id: 3,
        name: 'Avo Rein Tereping',
        email: 'avo.tereping1234@gmail.com',
        room: 'Zoom',
        birthdate: '1994-11-30',
        subject: 'Psühholoogia',
    },
    {
        id: 4,
        name: 'Laura Hein',
        email: 'laura.hein1234@gmail.com',
        room: '303',
        birthdate: '1975-07-19',
        subject: 'Disaini alused',
    },
    {
        id: 5,
        name: 'Mari Kuli',
        email: 'mari.kuli1234@gmail.com',
        room: '202',
        birthdate: '1977-02-14',
        subject: 'Inglise keel',
    },
    {
        id: 6,
        name: 'Andrus Rinde',
        email: 'andrus.rinde1234@gmail.com',
        room: '103',
        birthdate: '1988-08-23',
        subject: 'Multimeedium',
    },
    {
        id: 7,
        name: 'Martti Raavel',
        email: 'martti.raavel1234@gmail.com',
        room: '220',
        birthdate: '1980-12-01',
        subject: 'Programmeerimine I',
    },
];

module.exports = teachers;